spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common #, secret 
      
server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
      
server:
  port: 8080
  address: localhost
  
serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
      
server:
  port: 8080
  address: 52.78.112.137
  
serverName: blue_server
---

spring:
  config:
    activate:
      on-profile: green
      
server:
  port: 8081
  address: 52.78.112.137
  
serverName: green_server

---


spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:mysql://mall-mysql.cpcauwygsgm8.ap-northeast-2.rds.amazonaws.com:3306/mall_product_service #ec2 환경변수
    username: admin
    password: asdf1234
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 업데이트
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8에 맞는 dialect 설정
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
