server:
  port: 8081  # 이 서비스는 8081 포트를 사용

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username:
    password: 
  jpa:
    hibernate:
      ddl-auto: update  # 자동 테이블 생성
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true  # JSON 출력 포맷

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # SQL 로그 출력
