name: Trigger MALL-INFRA CICD

on:
  push:
    branches:
      - master

jobs:
  trigger-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Send event to MALL-INFRA
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               https://api.github.com/repos/ImHyukJin/MALL-INFRA/actions/workflows/deploy.yml/dispatches \
               -d '{"ref":"master","inputs":{"service":"mall_product"}}'
